version: '3.8'

services:
  web:
    image: wareagledocker/website-monitor
    container_name: website-monitor
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT_ID=
